export const Filters = {
  ALL: 'ALL',
  DIRECT: 'DIRECT',
  ONE_STOP: 'ONE_STOP',
  TWO_STOPS: 'TWO_STOPS',
  THREE_STOPS: 'THREE_STOPS',
};

export const SortTypes = {
  SHOW_CHEAPEST: 'SHOW_CHEAPEST',
  SHOW_FASTEST: 'SHOW_FASTEST',
};

export const REQUEST_TICKETS = 'REQUEST_TICKETS';
export const RECEIVE_TICKETS = 'RECEIVE_TICKETS';
export const RECEIVE_ERROR = 'RECEIVE_ERROR';


export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';